### ISSUE TITLE
Talk: share on social networks

### ISSUE THREAD

**Issue by kuusas** [ntacamp/notrollsallowed.com-event#11]
Įdėti Twitter ir Facebook share mygtukus pranešimo peržiūros puslapyje. Sutvakyti meta tagus, kad sharinant rodytu teisingą aprašymą.

**Comment by Pawka** [comment]
Gal prieš tai reiktų slug'us įmest pranešimams ir url pagal juos formuot?

**Comment by podolskis** [comment]
Nepamišti touch iconu tuo pačiu.
